"""Add parse_status to inbound_orders; backfill and clean up fabricated
matches for already-failed parses (ADR 0007)

Revision ID: 0008_parse_status
Revises: 0007_is_read
Create Date: 2026-07-30 00:00:00.000000
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = "0008_parse_status"
down_revision: Union[str, None] = "0007_is_read"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Schema: new column, defaulting existing + future rows to "success".
    op.add_column(
        "inbound_orders",
        sa.Column(
            "parse_status",
            sa.String(length=20),
            nullable=False,
            server_default="success",
        ),
    )

    # 2. Backfill: reclassify existing rows using the signal that was
    # already 100% reliable before this column existed (ADR 0007, Context)
    # — a populated parse_error means parse_message() raised outright.
    op.execute(
        """
        UPDATE inbound_orders
        SET parse_status = 'failed'
        WHERE parse_error IS NOT NULL
        """
    )

    # 3. Cleanup: delete the fabricated MatchResult rows this ADR exists to
    # stop producing. This is a genuine, irreversible data deletion — see
    # ADR 0007 Decision 5. It removes exactly the flat-neutral-score rows
    # generated by running the matching engine against an essentially empty
    # ParsedOrder for an order whose parse failed outright.
    op.execute(
        """
        DELETE FROM match_results
        WHERE order_id IN (
            SELECT id FROM inbound_orders WHERE parse_status = 'failed'
        )
        """
    )


def downgrade() -> None:
    # Data deleted in step 3 of upgrade() is not recoverable — downgrade
    # only reverses the schema change, per this repo's existing convention
    # for irreversible-data-cleanup migrations.
    op.drop_column("inbound_orders", "parse_status")
